name: Maven Build

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-java@v3.0.0
        with:
          distribution: adopt
          java-version: '8'
          cache: 'maven'

      - run: mvn package --file pom.xml
