name: Publish to GitHub Packages

on:
  workflow_dispatch: {}
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3.0.0

        - uses: actions/setup-java@v3.2.0
          with:
            distribution: adopt
            java-version: '8'
            cache: 'maven'

        - run: mvn deploy
