name: Create Release

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  release:
    if: github.repository_owner == 'ybw0014'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      with:
        distribution: adopt
        java-version: 17
        java-package: jdk
        architecture: x64

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: Get version
      id: run
      run: |
        newVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo New Version: $newVersion
        echo ::set-output name=new-version::$newVersion
        # Modified From: https://github.com/Bullrich/generate-release-changelog
        tag=$(git tag | sort -r --version-sort | head -n1)
        if [ "$tag" ]; then
          changelog=$(git log --oneline --no-decorate $tag..HEAD)
        else
          changelog=$(git log --oneline --no-decorate)
          tag="0.0.0"
        fi
        echo Old Version: $tag
        echo ::set-output name=old-version::$tag
        changelog="${changelog//'%'/'%25'}"
        changelog="${changelog//$'\n'/'%0A' - }"
        changelog=" - ${changelog//$'\r'/'%0D'}"
        echo "$changelog"
        echo ::set-output name=changelog::$changelog

    - name: Compare versions
      uses: madhead/semver-utils@v2.1.0
      id: comparison
      with:
        version: ${{ steps.run.outputs.new-version }}
        compare-to: ${{ steps.run.outputs.old-version }}

    - name: Create release
      uses: actions/create-release@v1.1.4
      if: steps.comparison.outputs.comparison-result == '>'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.run.outputs.new-version }}
        release_name: Release v${{ steps.run.outputs.new-version }}
        body: ${{ steps.run.outputs.changelog }}
